# Generated by Django 3.0 on 2023-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0015_auto_20231005_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='guards',
            name='rlevel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
