# Generated by Django 3.0 on 2023-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guards',
            name='passphoto',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='securityapp/'),
        ),
    ]
