# Generated by Django 3.0 on 2023-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0002_guards_passphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guards',
            name='status',
            field=models.CharField(blank=True, default='Not Updated Yet', max_length=100, null=True),
        ),
    ]
