# Generated by Django 3.0 on 2023-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0003_auto_20230928_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guards',
            name='passphoto',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guards',
            name='pic',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
