# Generated by Django 3.0 on 2023-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0005_auto_20230929_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='guardname',
            new_name='guard',
        ),
    ]
