# Generated by Django 3.0 on 2023-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0006_auto_20230929_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='contactno',
            field=models.CharField(blank=True, default='1234506789', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='timeperiod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
