# Generated by Django 3.0 on 2023-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0008_auto_20230930_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='fromdate',
            field=models.DateTimeField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='timings',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='todate',
            field=models.DateTimeField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='workplace',
            field=models.CharField(blank=True, default='work not assigned', max_length=100, null=True),
        ),
    ]
