# Generated by Django 3.0 on 2023-09-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0009_auto_20230930_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='timings',
            new_name='fromtime',
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='totime',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
