# Generated by Django 3.0 on 2023-10-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('securityapp', '0010_auto_20230930_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='guards',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='fromdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='fromtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='todate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackinghistory',
            name='totime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
