# Generated by Django 3.0 on 2023-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0012_auto_20231003_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='guards',
            name='issue',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='guards',
            name='level',
            field=models.CharField(blank=True, default='You are  not choosen any training Level', max_length=100, null=True),
        ),
    ]
