# Generated by Django 3.0 on 2023-10-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0013_auto_20231004_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='workplace',
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='workplacee',
            field=models.CharField(blank=True, default='work not assigned', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstatus', models.CharField(blank=True, default='Not Updated Yet', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='work not assigned', max_length=100, null=True)),
                ('contactno2', models.CharField(blank=True, default='1234506789', max_length=100, null=True)),
                ('fromtime', models.CharField(blank=True, max_length=100, null=True)),
                ('totime', models.CharField(blank=True, max_length=100, null=True)),
                ('fromdate', models.DateTimeField(blank=True, null=True)),
                ('todate', models.DateTimeField(blank=True, null=True)),
                ('guard2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securityapp.Guards')),
            ],
        ),
    ]
