# Generated by Django 3.0 on 2023-10-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0014_auto_20231005_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='workplacee',
            new_name='workplace',
        ),
    ]
