# Generated by Django 3.0 on 2023-10-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityapp', '0017_auto_20231005_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guards',
            name='level',
            field=models.CharField(blank=True, default='not get any training Level', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, default='Training not assigned', max_length=100, null=True),
        ),
    ]
